url: "https://example.com"
port: 8080

sources:
  # file source
  - id: "source_file_1"
    type: "file"
    file: "./audio.wav"

  # FM source
  - id: "source_fm_1"
    type: "fm"
    device: "hackrf=0"
    mid_frequency: 80000000

outputs:
  # file
  - source: "source_file_1"

  # FM
  - source: "source_fm_1"
    frequency: 80000000

  # FM with different frequency
  - source: "source_fm_1"
    frequency: 82500000
